# Generated by Django 5.2.18 on 2026-10-08 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('checked', models.BooleanField(default=False)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.productvariant')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping_lists.shoppinglist')),
            ],
            options={
                'ordering': ['checked', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('shopping_list', 'product_variant'), name='unique_variant_per_list'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='list_item_quantity_positive')],
            },
        ),
    ]
