# Generated by Django 5.2.18 on 2026-10-08 02:17

import apps.core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.now, editable=False),
        ),
    ]
