# Generated by Django 5.2.18 on 2026-10-09 01:48

import apps.core.clock
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('prices', '0002_alter_priceconfirmation_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('HIDE', 'Ocultar'), ('RESTORE', 'Restaurar'), ('UPHOLD', 'Manter oculto após recurso')], max_length=7)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=apps.core.clock.now, editable=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderations', to='prices.priceobservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=apps.core.clock.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appeal', to='moderation.pricemoderation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('CONFIRMED', 'Indício confirmado'), ('DISMISSED', 'Descartado')], max_length=9)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=apps.core.clock.now, editable=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='contributions.fraudsignal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricemoderation',
            index=models.Index(fields=['observation', '-created_at'], name='moderation__observa_6b8091_idx'),
        ),
    ]
