# Generated by Django 5.2.18 on 2026-10-08 02:33

import apps.core.clock
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_seed_categories'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(help_text='Texto exibido, ex.: 3 por R$ 20', max_length=120)),
                ('rule', models.JSONField()),
                ('valid_from', models.DateTimeField(default=apps.core.clock.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='products.productvariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'product_variant', 'is_active'], name='promotions__store_i_f4702b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='promotion_valid_until_after_from')],
            },
        ),
    ]
