# Generated by Django 5.2.18 on 2026-10-09 00:10

import apps.core.clock
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prices', '0002_alter_priceconfirmation_created_at_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Aguardando confirmação'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=10)),
                ('photo', models.FileField(blank=True, upload_to='contributions/%Y/%m/')),
                ('photo_sha256', models.CharField(db_index=True, max_length=64)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('extraction', models.JSONField(default=dict)),
                ('corrected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=apps.core.clock.now, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='prices.priceobservation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DUPLICATE_PHOTO', 'Foto já usada'), ('PRICE_OUTLIER', 'Preço muito fora do usual'), ('RATE_BURST', 'Muitas contribuições em pouco tempo'), ('LOCATION_FAR', 'Aparelho longe da loja'), ('LOCATION_MISSING', 'Localização não informada'), ('STALE_PHOTO', 'Foto antiga')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], max_length=6)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=apps.core.clock.now, editable=False)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fraud_signals', to='contributions.usercontribution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usercontribution',
            index=models.Index(fields=['user', 'status', '-created_at'], name='contributio_user_id_e9afc2_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudsignal',
            index=models.Index(fields=['kind', '-created_at'], name='contributio_kind_93fc1c_idx'),
        ),
    ]
