# Generated by Django 5.2.18 on 2026-10-08 02:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('payment_condition', models.CharField(choices=[('NORMAL', 'Preço normal'), ('PIX', 'Pix'), ('DEBIT', 'Débito'), ('CREDIT', 'Crédito'), ('LOYALTY', 'Clube de fidelidade'), ('COUPON', 'Cupom')], default='NORMAL', max_length=10)),
                ('is_promotional', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('MERCHANT', 'Informado pelo estabelecimento'), ('USER', 'Informado por consumidor'), ('FLYER', 'Encarte'), ('PUBLIC_SOURCE', 'Fonte pública'), ('HISTORICAL', 'Histórico'), ('CALCULATED', 'Estimativa calculada')], max_length=15)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('confidence_level', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], max_length=6)),
                ('location_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_observations', to='products.productvariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_observations', to='stores.store')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='prices.priceobservation')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PHOTO', 'Fotografia'), ('FLYER', 'Encarte'), ('URL', 'Link')], max_length=10)),
                ('file', models.FileField(blank=True, upload_to='evidence/%Y/%m/')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_url', models.URLField(blank=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='prices.priceobservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agrees', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='prices.priceobservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='priceobservation',
            index=models.Index(fields=['product_variant', 'store', '-collected_at'], name='prices_pric_product_ef527b_idx'),
        ),
        migrations.AddIndex(
            model_name='priceobservation',
            index=models.Index(fields=['store', '-collected_at'], name='prices_pric_store_i_c8bdc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('collected_at')), _connector='OR'), name='price_valid_until_after_collected'),
        ),
        migrations.AddConstraint(
            model_name='priceconfirmation',
            constraint=models.UniqueConstraint(fields=('observation', 'user'), name='one_confirmation_per_user'),
        ),
    ]
