# Generated by Django 5.2.18 on 2026-10-08 02:17

import apps.core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceconfirmation',
            name='created_at',
            field=models.DateTimeField(default=apps.core.clock.now, editable=False),
        ),
        migrations.AlterField(
            model_name='priceevidence',
            name='created_at',
            field=models.DateTimeField(default=apps.core.clock.now, editable=False),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='collected_at',
            field=models.DateTimeField(default=apps.core.clock.now),
        ),
        migrations.AlterField(
            model_name='priceobservation',
            name='created_at',
            field=models.DateTimeField(default=apps.core.clock.now, editable=False),
        ),
    ]
