# Generated by Django 5.2.18 on 2026-10-08 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em análise'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rejeitado'), ('SUSPENDED', 'Suspenso')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False), ('deleted_at__isnull', True)), fields=('cnpj',), name='merchant_unique_alive_cnpj')],
            },
        ),
        migrations.CreateModel(
            name='MerchantVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em análise'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rejeitado'), ('SUSPENDED', 'Suspenso')], max_length=20)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em análise'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rejeitado'), ('SUSPENDED', 'Suspenso')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MERCHANT_OWNER', 'Comerciante (proprietário)'), ('MERCHANT_MANAGER', 'Comerciante (gerente)'), ('MERCHANT_OPERATOR', 'Comerciante (operador)')], max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'user'), name='unique_merchant_member')],
            },
        ),
    ]
