# Generated by Django 5.2.18 on 2026-10-08 02:17

import apps.core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantverification',
            name='created_at',
            field=models.DateTimeField(default=apps.core.clock.now, editable=False),
        ),
    ]
