# Generated by Django 5.2.18 on 2026-10-08 02:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('store_type', models.CharField(choices=[('SUPERMARKET', 'Supermercado'), ('MINIMARKET', 'Mercadinho'), ('WHOLESALE', 'Atacado'), ('BAKERY', 'Padaria'), ('BUTCHER', 'Açougue'), ('GREENGROCER', 'Hortifruti'), ('PHARMACY', 'Farmácia'), ('OTHER', 'Outro')], default='OTHER', max_length=20)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=8)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa')], default='ACTIVE', max_length=10)),
                ('source', models.CharField(choices=[('MERCHANT', 'Comerciante'), ('OPENSTREETMAP', 'OpenStreetMap'), ('USER', 'Usuário')], default='MERCHANT', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='merchants.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'store_type'], name='stores_stor_status_81fed5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('external_id', ''), _negated=True), ('deleted_at__isnull', True)), fields=('source', 'external_id'), name='store_unique_alive_external_id')],
            },
        ),
    ]
