# Generated by Django 5.2.18 on 2026-10-08 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('price_ttl_hours', models.PositiveIntegerField(default=168)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('catalog_source', models.CharField(choices=[('MANUAL', 'Cadastro manual'), ('MERCHANT', 'Comerciante'), ('USER', 'Usuário'), ('OPEN_FOOD_FACTS', 'Open Food Facts')], default='MANUAL', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=120)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('gtin', models.CharField(blank=True, max_length=14, null=True)),
                ('label', models.CharField(blank=True, help_text='Ex.: Tipo 1', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'L'), ('un', 'un'), ('m', 'm')], max_length=2)),
                ('base_quantity', models.DecimalField(decimal_places=3, editable=False, max_digits=14)),
                ('base_unit', models.CharField(editable=False, max_length=2)),
                ('pack_count', models.PositiveSmallIntegerField(default=1)),
                ('identity_key', models.CharField(editable=False, max_length=64)),
                ('catalog_source', models.CharField(choices=[('MANUAL', 'Cadastro manual'), ('MERCHANT', 'Comerciante'), ('USER', 'Usuário'), ('OPEN_FOOD_FACTS', 'Open Food Facts')], default='MANUAL', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('normalized_name', 'brand'), name='product_unique_alive_name_brand', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('gtin__isnull', False)), fields=('gtin',), name='variant_unique_alive_gtin'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('identity_key',), name='variant_unique_alive_identity'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='variant_quantity_positive'),
        ),
    ]
